name: alpensw
description: "アルペン競技用のストップウォッチ"
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_riverpod:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

flutter_launcher_icons:
   android: true
   ios: true
   image_path: 'assets/images/icon.png'
   adaptive_icon_background: '#ffffff'
   adaptive_icon_foreground: 'assets/images/icon_adaptive_foreground.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png